---
# handlers file for /etc/ansible/roles/apache2
- name: Restart Apache
  hosts: all
  become: true
  tasks:
    - name: Restart Apache Service
      service:
        name: httpd
        state: restarted

